import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './features/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      spacing: {
        '62': '248px',
      },
      fontSize: {
        '2.5': '0.625rem',
        '3': ['0.75rem', { lineHeight: '1rem' }],
        '3.5': '0.875rem',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: { '1': 'hsl(var(--chart-1))', '2': 'hsl(var(--chart-2))', '3': 'hsl(var(--chart-3))', '4': 'hsl(var(--chart-4))', '5': 'hsl(var(--chart-5))', gpu: 'hsl(var(--chart-1))', vram: 'hsl(var(--chart-2))', cpu: 'hsl(var(--chart-3))', temp: 'hsl(var(--chart-4))' },
        surface: { '0': 'hsl(var(--surface-0))', '1': 'hsl(var(--surface-1))', '2': 'hsl(var(--surface-2))', '3': 'hsl(var(--surface-3))' },
        neon: { purple: 'hsl(var(--neon-purple))', blue: 'hsl(var(--neon-blue))', cyan: 'hsl(var(--neon-cyan))', pink: 'hsl(var(--neon-pink))', green: 'hsl(var(--neon-green))', amber: 'hsl(var(--neon-amber))' },
        'tripo-gray': {
          '1': 'hsl(var(--tripo-gray-1))',
          '2': 'hsl(var(--tripo-gray-2))',
          '3': 'hsl(var(--tripo-gray-3))',
          '4': 'hsl(var(--tripo-gray-4))',
          '100': 'hsl(var(--tripo-gray-100))',
          '200': 'hsl(var(--tripo-gray-200))',
          '300': 'hsl(var(--tripo-gray-300))',
        },
        'tripo-yellow': {
          '1': 'hsl(var(--tripo-yellow-1))',
        },
        'tripo-white': {
          '5': 'hsl(var(--tripo-white-5))',
          '10': 'hsl(var(--tripo-white-10))',
        },
        tooltip: { bg: 'hsl(var(--tooltip-bg))', border: 'hsl(var(--tooltip-border))', fg: 'hsl(var(--tooltip-fg))' },
        log: { info: 'hsl(var(--log-info))', success: 'hsl(var(--log-success))', warn: 'hsl(var(--log-warn))', error: 'hsl(var(--log-error))', debug: 'hsl(var(--log-debug))' },
        admin: { accent: 'hsl(var(--admin-accent))', 'accent-deep': 'hsl(var(--admin-accent-deep))' },
        status: { online: 'hsl(var(--status-online))', offline: 'hsl(var(--status-offline))', busy: 'hsl(var(--status-busy))' },
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-in-up': { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-in-down': { from: { opacity: '0', transform: 'translateY(-20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right': { from: { opacity: '0', transform: 'translateX(30px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'glow-pulse': { '0%, 100%': { opacity: '0.5' }, '50%': { opacity: '1' } },
        'border-glow': { '0%, 100%': { boxShadow: '0 0 5px hsl(var(--neon-purple) / 0.3), 0 0 10px hsl(var(--neon-purple) / 0.2)' }, '50%': { boxShadow: '0 0 20px hsl(var(--neon-purple) / 0.5), 0 0 40px hsl(var(--neon-purple) / 0.3)' } },
        'float': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        'spin-slow': { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        'progress-indeterminate': { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        'gradient-shift': { '0%, 100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        'aurora': { '0%': { transform: 'translate(0, 0) rotate(0deg)' }, '25%': { transform: 'translate(-20px, 20px) rotate(90deg)' }, '50%': { transform: 'translate(20px, -20px) rotate(180deg)' }, '75%': { transform: 'translate(-20px, -20px) rotate(270deg)' }, '100%': { transform: 'translate(0, 0) rotate(360deg)' } },
        'fadeIn': { 'from': { opacity: '0', transform: 'translateY(4px)' }, 'to': { opacity: '1', transform: 'translateY(0)' } },
        'glow-sweep': { '0%, 100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        'aura-flow': { '0%': { transform: 'translate(0px, 0px) scale(1) rotate(0deg)' }, '33%': { transform: 'translate(30px, -50px) scale(1.2) rotate(120deg)' }, '66%': { transform: 'translate(-20px, 20px) scale(0.8) rotate(240deg)' }, '100%': { transform: 'translate(0px, 0px) scale(1) rotate(360deg)' } },
        'energy-pulse': { '0%, 100%': { boxShadow: '0 0 15px rgba(245, 166, 35, 0.2)', borderColor: 'rgba(245, 166, 35, 0.3)' }, '50%': { boxShadow: '0 0 35px rgba(245, 166, 35, 0.6)', borderColor: 'rgba(245, 166, 35, 0.8)' } },
        'speed-lines-move': { '0%': { backgroundPosition: '0px 0px' }, '100%': { backgroundPosition: '1000px 0px' } }
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.4s ease-out',
        'fade-in-up': 'fade-in-up 0.5s ease-out',
        'fade-in-down': 'fade-in-down 0.5s ease-out',
        'slide-in-right': 'slide-in-right 0.4s ease-out',
        'scale-in': 'scale-in 0.3s ease-out',
        'shimmer': 'shimmer 2s linear infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'border-glow': 'border-glow 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'spin-slow': 'spin-slow 8s linear infinite',
        'progress-indeterminate': 'progress-indeterminate 1.5s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'aurora': 'aurora 20s ease-in-out infinite',
        'fadeIn': 'fadeIn 250ms cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'glow-sweep': 'glow-sweep 4s ease infinite',
        'aura-flow-1': 'aura-flow 25s infinite alternate ease-in-out',
        'aura-flow-2': 'aura-flow 20s infinite alternate-reverse ease-in-out',
        'energy-pulse': 'energy-pulse 2s infinite ease-in-out',
        'speed-lines': 'speed-lines-move 1.5s linear infinite'
      },
      boxShadow: {
        'glow-primary': '0 0 20px hsl(var(--primary) / 0.3), 0 0 40px hsl(var(--primary) / 0.15)',
        'glow-primary-lg': '0 0 30px hsl(var(--primary) / 0.4), 0 0 60px hsl(var(--primary) / 0.2)',
        'glow-purple': '0 0 20px hsl(var(--neon-purple) / 0.3), 0 0 40px hsl(var(--neon-purple) / 0.15)',
        'glow-blue': '0 0 20px hsl(var(--neon-blue) / 0.3), 0 0 40px hsl(var(--neon-blue) / 0.15)',
        'glow-cyan': '0 0 20px hsl(var(--neon-cyan) / 0.3), 0 0 40px hsl(var(--neon-cyan) / 0.15)',
        'card': '0 4px 24px -4px rgba(0, 0, 0, 0.4), 0 0 1px rgba(255, 255, 255, 0.05) inset',
        'card-hover': '0 8px 32px -4px rgba(0, 0, 0, 0.5), 0 0 1px rgba(255, 255, 255, 0.1) inset, 0 0 20px hsl(var(--primary) / 0.1)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;